name: 🚧 Build, lint & Release if version changed

on:
  push:
    branches: [main]

jobs:
  Build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: 📥 Checkout Commit
        uses: actions/checkout@v3

      - name: 🔍 Parse package.json
        id: packageInfo
        run: |
          echo "PACKAGE_NAME=$(jq -r .name package.json)" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: 🛠️ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧹 Run ESLint
        run: npm run lint

      - name: 🏗️ Build project
        run: npm run build:tsc

      - name: 🔖 Check if version tag already exists
        id: check_tag
        run: |
          git fetch --tags --force

          if git rev-parse "v$PACKAGE_VERSION" >/dev/null 2>&1; then
            echo "Tag v$PACKAGE_VERSION already exists. Skipping release."
            echo "should_release=false" >> $GITHUB_OUTPUT
          else
            echo "No tag for version v$PACKAGE_VERSION"
            echo "should_release=true" >> $GITHUB_OUTPUT
          fi

      - name: 🏷️ Create GitHub Release
        if: steps.check_tag.outputs.should_release == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          release_name: v${{ env.PACKAGE_VERSION }}
          draft: true
          prerelease: false
